### ISSUE TITLE
JB Content Review - Work in Progress

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect-messaging#1]
- [x] Intro Page

Feel there should be abit more business context on this page  or another business page within Overview section, explaining the business objectives/benefits that the capabilities are intended to deliver;  are there going to be Clinical Scenarios - to give example other business use cases, user stories as we've done with AM/Structured?

BD: this is covered under #3 

- [x] On graphic - as Send Doc is outlined different to Send Task/Update - some form of info about each capability, why the different outline etc, something about their 'evolution', 

BD: Added simple description of future capabilities to send task and send update pages. 

- [x ] Is it worth explaining anything about rationale for Mssaging rather than FHIR API - aha - could link to the Communication paradigm section on Design principles page

BD: Would like to keep the intro page simple. If a reader is thinking "why messaging" - Design approach menu seems an obvious choice

- [x] Spelling - in 2. Who's looking- 'seeding' vs 'seeking'

- [x] First of Type Page
The Summary sentence leaves out the concept of the 'receiver' systems also being assured etc

- [x] Glossary
Some stuff - eg 'GP Connect 'Licence' - terminology may have been superseded

- [x] Menu Items

The top level 'group' menu items when  clicked on don't present either their own page or the first page in the group 

BD: this follows the approach found on the gp connect fhir api site.

- [x] General

Should the term 'practice' meaning GP Practice have a capital P? to more quickly convey that its a 'proper noun' 

- [x] Design Principles Page
Re-usability section
The 'Send federated encounter summary' use case title quoted;  is this different or the same as 'Send federated consultation summary'?  if same, should only one term be used?- and on actual Use Case pages

BD: Changed wording and and linked to page

- [x] Implement a Capability
When navigating the menu under this and 'Send a Doc' One ends up at the 'Introduction' menu item, but the Group menu option of 'Send a Doc'  is no longer presented

BD: Added "Send Document" title to the Send Document left navbar following GP Connect FHIR API style

- [x] Message Payload Page
first para under the Payload diagram - if the word 'organisation' is plural, then the apostrophe should come after the 's' - ie organisations' records ......

- [x] In spec pages - use of 'MUST' vs 'SHALL' are these terms used intentionally for different reasons? - consistency across GPC as a whole?

**Comment by Mhitchins** [comment]
Hi Jackie, the word 'practice' is not a 'proper noun' so the p should be lower case.

**Comment by tim1ford** [comment]
@jackiebarnes with regards to the Menu Items top level group; we don't do this throughout the spec.

Perhaps this can be parked for the spec overhaul?

**Comment by briandiggle** [comment]
Re: MUST and SHALL  - under RFC 2119, these terms are equivalent.

**Comment by briandiggle** [comment]
All comments addressed
