### ISSUE TITLE
GP Connect Messaging - Design Principles page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#10]
- [x] Is the title GP Connect Messaging - Design Principles used to distinguish from GP Connect API design principles? I'd suggest GP Connect Messaging could be removed

- [x] Design Principles: "....updates to GP systems are facilitated" suggest use GP Principal Clinical Systems (also in other part so this page and throughout spec. could use PCS suppliers for short - confer with Mike H on this nomenclature) ...."GP core clinical system" referenced later
Asynchronous messaging paradigms: "Messages flowing into GP practices on MESH" suggest "Messages flowing into GP PCSs on MESH" 

- [x] 1. Point to point event notification: full stop missing after last para

- [x] 2. Publish/Subscribe event notification: "...will subscribe at an event hub..." suggest "...will subscribe through an event hub ..."

- [x] Messaging format : FHIR STU3 Messages: might be worth adding a line on why this was chosen, as you have for other decisions

- [x] Reliability: ITK3: full stop used after the first bullet point when probably should be at the end of the second one

- [x] Re-usability: Payload re-use: "...a particular use case, care has been ..." suggest comma isn't needed
"....fulfil other identified uses cases..." suggest "use cases"

**Comment by tim1ford** [comment]
@Mhitchins re: Richard's question above...can we use PCS?

**Comment by tim1ford** [comment]
All but the messaging format question is covered in https://github.com/nhsconnect/gpconnect-messaging/commit/027c0d7bc4632d896b05a9dc172a018fef629744
