### ISSUE TITLE
Send Document - Payload structure

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#11]
I suggest you don't need Send Document in page title

"....that for most scenarios, messages which are..." suggest comma isn't needed

General question - are the profiles linked out to just CC versions or the GPC flavour of these?

Fourth bullet: "Where the message contains patient information..." I think it should be "practitioner information"

**Comment by tim1ford** [comment]
https://github.com/nhsconnect/gpconnect-messaging/commit/a77316d0208e4140755d894b17ea73b2830fccaa

All points covered, will pick up the general question with Brian.
