### ISSUE TITLE
Send Federated Consultation Summary - Overview page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#12]
For this and other pages under this use case I'm not sure if Send Federated Consultation Summary is needed in the page title

"This use-case completes ..." suggest hyphen isn't needed

Detail in some of the boxes in the diagram are not readable

**Comment by tim1ford** [comment]
All comments covered in https://github.com/nhsconnect/gpconnect-messaging/commit/27b3dc50627ab24869afe83e0276f649fb63f362
