### ISSUE TITLE
Send Federated Consultation Summary - Payload page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#13]
"which form the payload. I.e. the resources" - the i in i.e. has been capitalised

Task resource: "resource" not capitalised here but is for other resources

Organization Resource: "...telephone number of that organization. I.e. an instance..." the i in i.e. has been capitalised

Practitioner Resource: "...element of the Task resource described above" needs a full stop at the end

**Comment by tim1ford** [comment]
All points covered off in https://github.com/nhsconnect/gpconnect-messaging/commit/ba0c70eead01d5cb2901e0fee080b114dd24f1a7#diff-39ade96ba5c3585943020240daf2b0d1
