### ISSUE TITLE
Send Federated Consultation Summary - MESH configuration page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#15]
"Please refer to Integration to MESH for an introduction to the use of MESH for GP Connect Messaging use-cases" suggest a full stop at the end

As per a comment on another issue, MUST and SHALL are used interchangeably. Is this on purpose?

**Comment by tim1ford** [comment]
Full stop has been added.

MUST vs SHALL still needs to be addressed.

**Comment by briandiggle** [comment]
According to [https://www.ietf.org/rfc/rfc2119.txt](https://www.ietf.org/rfc/rfc2119.txt) MUST and SHALL are equivalent terms. 

A quick check of the GP Connect FHIR API site reveals that both are used throughout the site.
