### ISSUE TITLE
Send Federated Consultation Summary - Send Trigger page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#17]
"involvement of a clinician The GP IT system..." capitalisation of The and also suggest using GP PCS

"all messages associated with that encounter can be identifier." suggest "identifier" should be "identified"

"...all messages for this use-case will..." suggest hyphen isn't needed

**Comment by tim1ford** [comment]
Covered in https://github.com/nhsconnect/gpconnect-messaging/commit/9591525b519cae8e544d266f8937be1453207206
