### ISSUE TITLE
Integration to MESH page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#19]
"...to the mailbox of the patient’s registered GP." suggest it needs "practice" at the end of this sentence

"TODO: Link out to MESH endpoint lookup service doco which contains error handling info." will this be done before publication?

**Comment by tim1ford** [comment]
Covered off in https://github.com/nhsconnect/gpconnect-messaging/commit/164d691d5eb9ab32715d725bd82a539c46e5e806

General comment about TODOs will be raised.
