### ISSUE TITLE
Use of the ITK3 to support GP Connect Messaging page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#20]
"...to provide message reliability facilitate alignment with practice workflow." I think this should say "...reliability and facilitate..."

"...builds on the FHIR Messaging framework by through..." don't think "by" is needed

Third bullet needs a full stop at the end

"Please refer to the messaging capability and messaging use case pages..." messaging capability? do you mean Send Document capability?

**Comment by tim1ford** [comment]
Covered off in https://github.com/nhsconnect/gpconnect-messaging/commit/26572de88d85055601edbb1f2959c55c191dc124

Final comment not actioned, not being specific to Send Document will allow other capabilities to be added with re-addressing this section in the future.
