### ISSUE TITLE
Using ITK3 - add hyperlinks?

### ISSUE THREAD

**Issue by Mhitchins** [nhsconnect/gpconnect-messaging#24]
Would be good to link to the use cases in the following sentence (maybe in next iteration?)

Please refer to the messaging capability and messaging use case pages for details of which of these options is mandated or recommended for the particular message being created.

**Comment by tim1ford** [comment]
Cover in https://github.com/nhsconnect/gpconnect-messaging/commit/99967ea625e190623d687f866767defd3d4597d2
