### ISSUE TITLE
Introduction to GP Connect Messaging page

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-messaging#27]
In the following section:

http://gpconnect-messaging.netlify.com/#whos-looking

The following text:

"2. Message receivers: NHS organisations seeding to receive and process messages"

Should this not be more specific and say "GP practices seeking to receive and process messages".

It sounds like anyone can be a receiver, which is not true?

**Comment by tim1ford** [comment]
Covered in https://github.com/nhsconnect/gpconnect-messaging/commit/1d9913fea3e9a1b0d6d5ce0a90326f76f848c5bc#diff-d680e8a854a7cbad6d490c445cba2eba
