### ISSUE TITLE
Banner text capitalisation

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-messaging#28]
Following text in the version banner:

"If you're looking for the GP **connect** FHIR® API, please visit GP Connect Specification Versions"

The word **connect** needs capitalising.

**Comment by tim1ford** [comment]
Covered in https://github.com/nhsconnect/gpconnect-messaging/commit/0d681cdc7b4fa829cdd0ca91a5f9bd4e74825131
