### ISSUE TITLE
Business Requirements

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect-messaging#3]
Will need to add in the business requirements documentation being produced by Jim.

**Comment by tim1ford** [comment]
@MikeStacey are these being produced in markdown format or excel?

**Comment by MikeStacey** [comment]
@tim1ford  the requirements catalogue will be in excel. We are writing the processes in word/visio and will need to agree how they best fit on the site.

**Comment by tim1ford** [comment]
@jimphelps1 are the business requirements available to be linked to yet?

**Comment by jimphelps1** [comment]
@tim1ford This will be my main task for next week.

**Comment by tim1ford** [comment]
Business requirements and links to technical requirements have now been incorporated into the 1.2.0 specification.
