### ISSUE TITLE
NHS number verification by the sender?

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-messaging#30]
This has probably already has an answer, but is the sender required to verify/cross check the NHS number and demographics against PDS?

Is this automatically performed by the MESH client?

**Comment by briandiggle** [comment]
Where the MESH Endpoint Lookup Service is used (as described at https://nhsconnect.github.io/gpconnect-messaging/integration_mesh.html#message-routing-to-registered-practice), the MESH _server_ performs a PDS trace to verify the supplied demographic details and resolve the ODS code of the registered practice.

For the "Send federated consultation summary" use case, the use of the MESH endpoint lookup service is mandated.

Additionally, for the "Send federated consultation summary" use case, the message sender performs the following steps to ascertain whether a message should be sent to the registered practice:

1. If the patient registration type of the patient record at the appointment hosting practice is Regular (GMS/PMS) then no further action is required. (I.e. the registered practice care record is already up-to-date)
2. Perform a PDS lookup of the patient to determine the ODS code of the registered practice of the patient.
3. The system at the appointment hosting practice determines whether the registered practice is in the same federation as the hosting organisation ODS code using the local federation definition. This is consistent with the federation discoverability architectural foundations for the GP Connect Appointment Management capability as set out at https://nhsconnect.github.io/gpconnect/appointments_design.html#responsibilities-in-a-federated-booking-context
If this check passes, a “send encounter summary” message is sent.
