### ISSUE TITLE
Content of PDF

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-messaging#31]
Have rules for the content of the PDF been determined for the Federated Writeback use case been determined yet?

Are there any overarching rules that apply to all PDFs sent via send document?  For example, if a document is about a patient, a patient banner should appear on each page of the PDF document.

**Comment by briandiggle** [comment]
@jimphelps1  is looking at this area

**Comment by jimphelps1** [comment]
The PDF for the write-back use case has been designed and is awaiting sign-off from our clinical leads. More information to follow once it has been approved.

**Comment by tim1ford** [comment]
The agreed PDF and PDF requirements have now been incorporated into the 1.2.0 specification.
