### ISSUE TITLE
Use cases specific specifications

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect-messaging#4]
How much of what is described under the use case is generic and how much is linked to just that use case.

If these requirements are more generic then it would be better to identify them as such. This will help show to commonalty of the approach and make adding future use cases simpler in the future..

**Comment by briandiggle** [comment]
Some of the information under the use case may well turn out to apply to all "Send Document" use cases.

As the specification evolves, it is likely that we will need to move generic requirements up to the "Send Docuement" level. At this stage, for simplicity of viewing for message senders, it has been left under the one use case.
