### ISSUE TITLE
Task and DocumentReference level 2 profiles

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect-messaging#43]
Data standards to create un-curated Level 2 profile for Task as per RK suggestion

Changes required to align when this is set up.

**Comment by briandiggle** [comment]
As no curated level 2 (careconnect) profiles exist, the following profiles have been created, and will be published on the NHS FHIR reference server imminently:

https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-Task-1
https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-DocumentReference-1

**Comment by swk003** [comment]
Given the minimal constraints to be applied to the  GPConnect DocumentReference profile (https://nhsconnect.github.io/gpconnect-messaging/senddocument_payload.html#including-documents-in-the-payload) would it not make sense to rename the profile to allow easier reuse across NHSD API estate?

**Comment by briandiggle** [comment]
For the moment a CareConnect-DocumentReference-1 profile is not an available option  - this would have been preferable.
