### ISSUE TITLE
Introduction page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#7]
In the second red box suggest changing 'those engaged with NHS Digital in First of Type activities' to 'those engaged with NHS Digital on design and pre-development activities'

Alison raised this already but we should be moving away from GP Practice IT systems to GP Principal Clinical Systems as part of the nomenclature.

"...set of capabilities, called GP Connect Messaging" suggest "....set of capabilities, under the badge GP Connect Messaging" or "....set of capabilities, dubbed GP Connect Messaging"

Using Messaging to perform update: "...updates to patient data" will it always be patient data being updated? could it just be information about a future appointment for example.

Who’s looking?: "...will be interested in this specification" suggest "...will be interested in these capabilities"

**Comment by tim1ford** [comment]
Closing based on updates made in:

https://github.com/nhsconnect/gpconnect-messaging/commit/9300260e776c766866ab18fce32711799eed2219#diff-d680e8a854a7cbad6d490c445cba2eba
