### ISSUE TITLE
Capabilities page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#8]
Not suggesting copying the API site but making the names of the capabilities stand out more would good

**Comment by tim1ford** [comment]
Added > to define the list of capabilities.

Added the roadmap callout to highlight future roadmap items.

https://github.com/nhsconnect/gpconnect-messaging/commit/edde6dde694c68b5694dfe4e8c50b725492104e4#diff-2766730664d8d4037f17591b03dac9e6
