### ISSUE TITLE
First of Type page

### ISSUE THREAD

**Issue by RiChallinor** [nhsconnect/gpconnect-messaging#9]
Might be worth putting a holding message at the bottom "Further FoT guidance is in the process of being defined and information will be added to this page in future releases"

**Comment by tim1ford** [comment]
Added info callout with the above text.

https://github.com/nhsconnect/gpconnect-messaging/commit/cc8123c5cd0da5b269e9415f349668b4c37f8dd4

**Comment by briandiggle** [comment]
Duplicate of #29
